version: '3'
services:
  mongo-db:
    container_name: mongo-db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mongo-db
    ports:
      - 27018:27017
    volumes:
      - ./shared:/shared
